### ISSUE TITLE
[SceneKit] Error: C3DProgramHashCodeStoreRegisterProgramForRendererElement - index out of capacity (8192 > 8192)

### ISSUE THREAD

**Issue by taichi729** [stevenroach7/3DScanr#2]
Hi, 
<img width="447" alt="screen shot 2019-02-25 at 4 27 59" src="https://user-images.githubusercontent.com/17064702/53304173-cf51ee80-38b5-11e9-97ed-8b491717c603.png">

I found this issue after i update my iphone ios to 12.
This ERROR pop on after reconstructbutton tapped and crash. 
but it seem to work sometime by capture the points for just a little.

Please Help, i really love this project but i am too stupid to fix by myself.
and sorry for bad english.

**Comment by taichi729** [comment]
My bad 
I found out the solution
<img width="662" alt="screen shot 2019-02-28 at 14 31 42" src="https://user-images.githubusercontent.com/17064702/53543309-9fc90d80-3b65-11e9-98e6-28d22f75fbe6.png">
just change this line to something smaller than 5 is just work fine

**Comment by hthaivu** [comment]
Hey Taichi! Thank you for following our project. We have been putting it on a pause for a bit, but I'm slowly back to the action now. 

It used to be working with Depth of 6, or even higher. This has been an issue since ARKit updated. We have been trying to see why it's the case but not yet found a solution.
